- name: Adicionar repositório Helm do Prometheus
  shell: |
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update

- name: Instalar Prometheus
  shell: |
    helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace
  args:
    creates: /usr/local/bin/helm
